// SPDX-License-Identifier: MIT
// Copyright (c) Igor Hipolito Vieira
//
// Generated from accesskit-c 0.23.0's include/accesskit.h. The values are ordinals in a
// C enum, so they are positional: regenerate this file when the vendored binary is
// updated rather than adding members by hand. AccessKitRoleMapTest pins the handful the
// bridge actually maps to, which is what would catch a silent renumbering.

namespace Forma.Accessibility
{
    /// <summary>A node's role, as AccessKit models it.</summary>
    internal enum AccessKitRole : byte
    {
        Unknown = 0,
        TextRun = 1,
        Cell = 2,
        Label = 3,
        Image = 4,
        Link = 5,
        Row = 6,
        ListItem = 7,
        ListMarker = 8,
        TreeItem = 9,
        ListBoxOption = 10,
        MenuItem = 11,
        MenuListOption = 12,
        Paragraph = 13,
        GenericContainer = 14,
        CheckBox = 15,
        RadioButton = 16,
        TextInput = 17,
        Button = 18,
        DefaultButton = 19,
        Pane = 20,
        RowHeader = 21,
        ColumnHeader = 22,
        RowGroup = 23,
        List = 24,
        Table = 25,
        LayoutTableCell = 26,
        LayoutTableRow = 27,
        LayoutTable = 28,
        Switch = 29,
        Menu = 30,
        MultilineTextInput = 31,
        SearchInput = 32,
        DateInput = 33,
        DateTimeInput = 34,
        WeekInput = 35,
        MonthInput = 36,
        TimeInput = 37,
        EmailInput = 38,
        NumberInput = 39,
        PasswordInput = 40,
        PhoneNumberInput = 41,
        UrlInput = 42,
        Abbr = 43,
        Alert = 44,
        AlertDialog = 45,
        Application = 46,
        Article = 47,
        Audio = 48,
        Banner = 49,
        Blockquote = 50,
        Canvas = 51,
        Caption = 52,
        Caret = 53,
        Code = 54,
        ColorWell = 55,
        ComboBox = 56,
        EditableComboBox = 57,
        Complementary = 58,
        Comment = 59,
        ContentDeletion = 60,
        ContentInsertion = 61,
        ContentInfo = 62,
        Definition = 63,
        DescriptionList = 64,
        Details = 65,
        Dialog = 66,
        DisclosureTriangle = 67,
        Document = 68,
        EmbeddedObject = 69,
        Emphasis = 70,
        Feed = 71,
        FigureCaption = 72,
        Figure = 73,
        Footer = 74,
        Form = 75,
        Grid = 76,
        GridCell = 77,
        Group = 78,
        Header = 79,
        Heading = 80,
        Iframe = 81,
        IframePresentational = 82,
        ImeCandidate = 83,
        Keyboard = 84,
        Legend = 85,
        LineBreak = 86,
        ListBox = 87,
        Log = 88,
        Main = 89,
        Mark = 90,
        Marquee = 91,
        Math = 92,
        MenuBar = 93,
        MenuItemCheckBox = 94,
        MenuItemRadio = 95,
        MenuListPopup = 96,
        Meter = 97,
        Navigation = 98,
        Note = 99,
        PluginObject = 100,
        ProgressIndicator = 101,
        RadioGroup = 102,
        Region = 103,
        RootWebArea = 104,
        Ruby = 105,
        RubyAnnotation = 106,
        ScrollBar = 107,
        ScrollView = 108,
        Search = 109,
        Section = 110,
        SectionFooter = 111,
        SectionHeader = 112,
        Slider = 113,
        SpinButton = 114,
        Splitter = 115,
        Status = 116,
        Strong = 117,
        Suggestion = 118,
        SvgRoot = 119,
        Tab = 120,
        TabList = 121,
        TabPanel = 122,
        Term = 123,
        Time = 124,
        Timer = 125,
        TitleBar = 126,
        Toolbar = 127,
        Tooltip = 128,
        Tree = 129,
        TreeGrid = 130,
        Video = 131,
        WebView = 132,
        Window = 133,
        PdfActionableHighlight = 134,
        PdfRoot = 135,
        GraphicsDocument = 136,
        GraphicsObject = 137,
        GraphicsSymbol = 138,
        DocAbstract = 139,
        DocAcknowledgements = 140,
        DocAfterword = 141,
        DocAppendix = 142,
        DocBackLink = 143,
        DocBiblioEntry = 144,
        DocBibliography = 145,
        DocBiblioRef = 146,
        DocChapter = 147,
        DocColophon = 148,
        DocConclusion = 149,
        DocCover = 150,
        DocCredit = 151,
        DocCredits = 152,
        DocDedication = 153,
        DocEndnote = 154,
        DocEndnotes = 155,
        DocEpigraph = 156,
        DocEpilogue = 157,
        DocErrata = 158,
        DocExample = 159,
        DocFootnote = 160,
        DocForeword = 161,
        DocGlossary = 162,
        DocGlossRef = 163,
        DocIndex = 164,
        DocIntroduction = 165,
        DocNoteRef = 166,
        DocNotice = 167,
        DocPageBreak = 168,
        DocPageFooter = 169,
        DocPageHeader = 170,
        DocPageList = 171,
        DocPart = 172,
        DocPreface = 173,
        DocPrologue = 174,
        DocPullquote = 175,
        DocQna = 176,
        DocSubtitle = 177,
        DocTip = 178,
        DocToc = 179,
        ListGrid = 180,
        Terminal = 181,
    }

    /// <summary>An action an assistive technology can request of a node.</summary>
    internal enum AccessKitAction : byte
    {
        Click = 0,
        Focus = 1,
        Blur = 2,
        Collapse = 3,
        Expand = 4,
        CustomAction = 5,
        Decrement = 6,
        Increment = 7,
        HideTooltip = 8,
        ShowTooltip = 9,
        ReplaceSelectedText = 10,
        ScrollDown = 11,
        ScrollLeft = 12,
        ScrollRight = 13,
        ScrollUp = 14,
        ScrollIntoView = 15,
        ScrollToPoint = 16,
        SetScrollOffset = 17,
        SetTextSelection = 18,
        SetSequentialFocusNavigationStartingPoint = 19,
        SetValue = 20,
        ShowContextMenu = 21,
    }

    /// <summary>Tri-state for a checkable node.</summary>
    internal enum AccessKitToggled : byte
    {
        False = 0,
        True = 1,
        Mixed = 2,
    }
}
