<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>Forma.Xaml.Compiler</AssemblyName>
    <RootNamespace>Forma.Xaml.Compiler</RootNamespace>
    <IsPackable>false</IsPackable>
    <DefineConstants Condition="'$(FormaRuntime)' == 'FNA'">$(DefineConstants);FORMA_FNA</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Forma/Forma.csproj" AdditionalProperties="FormaRuntime=$(FormaRuntime);MonoGameProjectPath=$(MonoGameProjectPath)" />
    <ProjectReference Include="../../external/XamlX/src/XamlX/XamlX.csproj" />
    <ProjectReference Include="../../external/XamlX/src/XamlX.IL.Cecil/XamlX.IL.Cecil.csproj" />
    <PackageReference Include="Mono.Cecil" Version="0.11.6" />
  </ItemGroup>

</Project>